version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:8080"
    depends_on:
      - database
      - cache
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  database:
    build: ./database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  cache:
    build: ./cache
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
